---
kind: pipeline
name: testing

platform:
  os: linux
  arch: amd64

steps:
- name: vet
  pull: always
  image: golang:1.14
  commands:
  - go vet ./...
  environment:
    GO111MODULE: on

- name: test
  pull: always
  image: golang:1.14
  commands:
  - go test -cover ./...
  environment:
    GO111MODULE: on

trigger:
  branch:
  - master

---
kind: pipeline
name: linux-amd64

platform:
  os: linux
  arch: amd64

steps:
- name: build-push
  pull: always
  image: golang:1.14
  commands:
  - "go build -a -tags netgo -o release/linux/amd64/drone-teams ./cmd/drone-teams"
  environment:
    CGO_ENABLED: 0
    GO111MODULE: on
  when:
    event:
    - push
    - pull_request
    - tag

- name: executable
  pull: always
  image: golang:1.14
  commands:
  - ./release/linux/amd64/drone-teams --help

- name: publish
  pull: always
  image: plugins/docker:linux-amd64
  settings:
    auto_tag: true
    dockerfile: docker/Dockerfile.linux.amd64
    password:
      from_secret: docker_password
    repo: jdamata/drone-teams
    username:
      from_secret: docker_username
  when:
    event:
    - push
    - tag
    
trigger:
  branch:
  - master

depends_on:
- testing
