---
kind: pipeline
name: linux-arm64

platform:
  os: linux
  arch: arm64

steps:
- name: docker-build-push
  pull: always
  image: golang:1.13
  commands:
  - "go get -v -t -d ./..."
  - "TAG=$(git rev-parse --short HEAD)"
  - "docker build -t jdamata/drone-teams:$TAG -t jdamata/drone-teams:latest ."
  - "echo $DOCKER_PASSWORD | docker login -u $DOCKER_LOGIN --password-stdin"
  - "docker push jdamata/drone-teams:$TAG"
  - "docker push jdamata/drone-teams:latest"
  environment:
    GO111MODULE: on

trigger:
  branch:
  - master
